apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: messager
data:
  init-db.sql: |
    CREATE DATABASE messager_users;
    CREATE DATABASE messager_messages;
    GRANT ALL PRIVILEGES ON DATABASE messager_users TO messager;
    GRANT ALL PRIVILEGES ON DATABASE messager_messages TO messager;